In [1]:
import requests
from pprint import pprint as pp
import pandas as pd

In [2]:
# https://cryptingup.com/apidoc/#introduction
response = requests.get('https://cryptingup.com/api/assets/?ID=btc')
main_info = response.json()

In [3]:
crytocurrency_df = pd.DataFrame(columns=['coin','price','one hour change','one day change', 'one week change', 'update'])
crytocurrency_df

Empty DataFrame
Columns: [coin, price, one hour change, one day change, one week change, update]
Index: []

In [4]:
first_main_info = main_info['assets'][0]

first_id = main_info['assets'][0]['asset_id']
first_price = main_info['assets'][0]['price']
first_change_1h = main_info['assets'][0]['change_1h']
first_change_24h = main_info['assets'][0]['change_24h']
first_change_7d = main_info['assets'][0]['change_7d']

first_created_at = main_info['assets'][0]['created_at']
first_description = main_info['assets'][0]['description']
first_updated_at = main_info['assets'][0]['updated_at']

In [5]:
def get_first_currency(main_info):
    first_main_info = main_info['assets'][0]
    first_id = main_info['assets'][0]['asset_id']
    first_price = main_info['assets'][0]['price']
    first_change_1h = main_info['assets'][0]['change_1h']
    first_change_24h = main_info['assets'][0]['change_24h']
    first_change_7d = main_info['assets'][0]['change_7d']
    first_created_at = main_info['assets'][0]['created_at']
    first_description = main_info['assets'][0]['description']
    first_updated_at = main_info['assets'][0]['updated_at']

    return first_main_info, first_id, first_price, first_change_1h, first_change_24h, first_change_7d, first_updated_at

In [6]:
class First:

    for coin in first_main_info:
        print(first_id)
        break
    for price in first_main_info:
        print(first_price)
        break
    for one_hour_change in first_main_info:
        print(first_change_1h)
        break
    for one_day_change in first_main_info:
        print(first_change_24h)
        break
    for one_week_change in first_main_info:
        print(first_change_7d)
        break
    for update in first_main_info:
        print(first_updated_at)
        break

USDT
1.0004949999847388
-0.013991117144660463
0.04599838905072875
0.05000025132901641
2023-02-13T15:11:15.461308

In [7]:
crytocurrency_df = crytocurrency_df.append({'coin': first_id,
                                            'price': first_price,
                                            'one hour change': first_change_1h,
                                            'one day change': first_change_24h,
                                            'one week change': first_change_7d,
                                            'update':first_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/2166909319.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': first_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.05,2023-02-13T15:11:15.461308

In [8]:
second_main_info = main_info['assets'][1]

second_id = main_info['assets'][1]['asset_id']
second_price = main_info['assets'][1]['price']
second_change_1h = main_info['assets'][1]['change_1h']
second_change_24h = main_info['assets'][1]['change_24h']
second_change_7d = main_info['assets'][1]['change_7d']

second_created_at = main_info['assets'][1]['created_at']
second_description = main_info['assets'][1]['description']
second_updated_at = main_info['assets'][1]['updated_at']

In [9]:
class Second:

    for coin in second_main_info:
        print(second_id)
        break
    for price in second_main_info:
        print(second_price)
        break
    for one_hour_change in second_main_info:
        print(second_change_1h)
        break
    for one_day_change in second_main_info:
        print(second_change_24h)
        break
    for one_week_change in second_main_info:
        print(second_change_7d)
        break
    for update in second_main_info:
        print(second_updated_at)
        break

BTC
21623.895096397122
0.0531966020702034
-1.2648105950115267
-5.328866686395213
2023-02-13T15:12:11.607444

In [10]:
crytocurrency_df = crytocurrency_df.append({'coin': second_id,
                                            'price': second_price,
                                            'one hour change': second_change_1h,
                                            'one day change': second_change_24h,
                                            'one week change': second_change_7d,
                                            'update':second_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/403869589.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': second_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444

In [11]:
third_main_info = main_info['assets'][2]

third_id = main_info['assets'][2]['asset_id']
third_price = main_info['assets'][2]['price']
third_change_1h = main_info['assets'][2]['change_1h']
third_change_24h = main_info['assets'][2]['change_24h']
third_change_7d = main_info['assets'][2]['change_7d']

third_created_at = main_info['assets'][2]['created_at']
third_description = main_info['assets'][2]['description']
third_updated_at = main_info['assets'][2]['updated_at']

In [12]:
class Third:

    for coin in third_main_info:
        print(third_id)
        break
    for price in third_main_info:
        print(third_price)
        break
    for one_hour_change in third_main_info:
        print(third_change_1h)
        break
    for one_day_change in third_main_info:
        print(third_change_24h)
        break
    for one_week_change in third_main_info:
        print(third_change_7d)
        break
    for update in third_main_info:
        print(third_updated_at)
        break

BUSD
0.9984999999999999
-0.10005002501252853
-0.10005002501253964
-0.10005002501252853
2023-02-13T15:12:11.696055

In [13]:
crytocurrency_df = crytocurrency_df.append({'coin': third_id,
                                            'price': third_price,
                                            'one hour change': third_change_1h,
                                            'one day change': third_change_24h,
                                            'one week change': third_change_7d,
                                            'update':third_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/1545298032.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': third_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055

In [14]:
fourth_main_info = main_info['assets'][3]

fourth_id = main_info['assets'][3]['asset_id']
fourth_price = main_info['assets'][3]['price']
fourth_change_1h = main_info['assets'][3]['change_1h']
fourth_change_24h = main_info['assets'][3]['change_24h']
fourth_change_7d = main_info['assets'][3]['change_7d']

fourth_created_at = main_info['assets'][3]['created_at']
fourth_description = main_info['assets'][3]['description']
fourth_updated_at = main_info['assets'][3]['updated_at']

In [15]:
class Fourth:

    for coin in fourth_main_info:
        print(fourth_id)
        break
    for price in fourth_main_info:
        print(fourth_price)
        break
    for one_hour_change in fourth_main_info:
        print(fourth_change_1h)
        break
    for one_day_change in fourth_main_info:
        print(fourth_change_24h)
        break
    for one_week_change in fourth_main_info:
        print(fourth_change_7d)
        break
    for update in fourth_main_info:
        print(fourth_updated_at)
        break

ETH
1484.0299999999997
0.16164574945918034
-3.0761667352192408
-8.912762584354933
2023-02-13T15:12:12.474254

In [16]:
crytocurrency_df = crytocurrency_df.append({'coin': fourth_id,
                                            'price': fourth_price,
                                            'one hour change': fourth_change_1h,
                                            'one day change': fourth_change_24h,
                                            'one week change': fourth_change_7d,
                                            'update':fourth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/462955676.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': fourth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254

In [17]:
fifth_main_info = main_info['assets'][4]

fifth_id = main_info['assets'][4]['asset_id']
fifth_price = main_info['assets'][4]['price']
fifth_change_1h = main_info['assets'][4]['change_1h']
fifth_change_24h = main_info['assets'][4]['change_24h']
fifth_change_7d = main_info['assets'][4]['change_7d']

fifth_created_at =  main_info['assets'][4]['created_at']
fifth_description = main_info['assets'][4]['description']
fifth_updated_at = main_info['assets'][4]['updated_at']

In [18]:
class Fifth:

    for coin in fifth_main_info:
        print(fifth_id)
        break
    for price in fifth_main_info:
        print(fifth_price)
        break
    for one_hour_change in fifth_main_info:
        print(fifth_change_1h)
        break
    for one_day_change in fifth_main_info:
        print(fifth_change_24h)
        break
    for one_week_change in fifth_main_info:
        print(fifth_change_7d)
        break
    for update in fifth_main_info:
        print(fifth_updated_at)
        break

BNB
290.2978811576749
-0.16473845687729635
-6.128171068905743
-11.577925111790687
2023-02-13T15:12:11.471437

In [19]:
crytocurrency_df = crytocurrency_df.append({'coin': fifth_id,
                                            'price': fifth_price,
                                            'one hour change': fifth_change_1h,
                                            'one day change': fifth_change_24h,
                                            'one week change': fifth_change_7d,
                                            'update':fifth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/1698772274.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': fifth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437

In [20]:
sixth_main_info = main_info['assets'][5]

sixth_id = main_info['assets'][5]['asset_id']
sixth_price = main_info['assets'][5]['price']
sixth_change_1h = main_info['assets'][5]['change_1h']
sixth_change_24h = main_info['assets'][5]['change_24h']
sixth_change_7d = main_info['assets'][5]['change_7d']

sixth_created_at =  main_info['assets'][5]['created_at']
sixth_description = main_info['assets'][5]['description']
sixth_updated_at = main_info['assets'][5]['updated_at']

In [21]:
class Sixth:

    for coin in sixth_main_info:
        print(sixth_id)
        break
    for price in sixth_main_info:
        print(sixth_price)
        break
    for one_hour_change in sixth_main_info:
        print(sixth_change_1h)
        break
    for one_day_change in sixth_main_info:
        print(sixth_change_24h)
        break
    for one_week_change in sixth_main_info:
        print(sixth_change_7d)
        break
    for update in sixth_main_info:
        print(sixth_updated_at)
        break

SOL
20.565613271618503
0.3984698441452212
-2.2459665443839474
-11.069512931256574
2023-02-13T15:11:14.823134

In [22]:
crytocurrency_df = crytocurrency_df.append({'coin': sixth_id,
                                            'price': sixth_price,
                                            'one hour change': sixth_change_1h,
                                            'one day change': sixth_change_24h,
                                            'one week change': sixth_change_7d,
                                            'update':sixth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/3619653181.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': sixth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437
5,SOL,20.565613,0.398470,-2.245967,-11.069513,2023-02-13T15:11:14.823134

In [23]:
seventh_main_info = main_info['assets'][6]

seventh_id = main_info['assets'][6]['asset_id']
seventh_price = main_info['assets'][6]['price']
seventh_change_1h = main_info['assets'][6]['change_1h']
seventh_change_24h = main_info['assets'][6]['change_24h']
seventh_change_7d = main_info['assets'][6]['change_7d']

seventh_created_at =  main_info['assets'][6]['created_at']
seventh_description = main_info['assets'][6]['description']
seventh_updated_at = main_info['assets'][6]['updated_at']

In [24]:
class Seventh:

    for coin in seventh_main_info:
        print(seventh_id)
        break
    for price in seventh_main_info:
        print(seventh_price)
        break
    for one_hour_change in seventh_main_info:
        print(seventh_change_1h)
        break
    for one_day_change in seventh_main_info:
        print(seventh_change_24h)
        break
    for one_week_change in seventh_main_info:
        print(seventh_change_7d)
        break
    for update in seventh_main_info:
        print(seventh_updated_at)
        break

MATIC
1.1680432617023282
-0.10904825562494279
-8.656572234104582
-2.9580341141358293
2023-02-13T15:12:14.154960

In [25]:
crytocurrency_df = crytocurrency_df.append({'coin': seventh_id,
                                            'price': seventh_price,
                                            'one hour change': seventh_change_1h,
                                            'one day change': seventh_change_24h,
                                            'one week change': seventh_change_7d,
                                            'update':seventh_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/2530204870.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': seventh_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437
5,SOL,20.565613,0.398470,-2.245967,-11.069513,2023-02-13T15:11:14.823134
6,MATIC,1.168043,-0.109048,-8.656572,-2.958034,2023-02-13T15:12:14.154960

In [26]:
eighth_main_info = main_info['assets'][7]

eighth_id = main_info['assets'][7]['asset_id']
eighth_price = main_info['assets'][7]['price']
eighth_change_1h = main_info['assets'][7]['change_1h']
eighth_change_24h = main_info['assets'][7]['change_24h']
eighth_change_7d = main_info['assets'][7]['change_7d']

eighth_created_at =  main_info['assets'][7]['created_at']
eighth_description = main_info['assets'][7]['description']
eighth_updated_at = main_info['assets'][7]['updated_at']

In [27]:
class Eighth:

    for coin in eighth_main_info:
        print(eighth_id)
        break
    for price in eighth_main_info:
        print(eighth_price)
        break
    for one_hour_change in eighth_main_info:
        print(eighth_change_1h)
        break
    for one_day_change in eighth_main_info:
        print(eighth_change_24h)
        break
    for one_week_change in eighth_main_info:
        print(eighth_change_7d)
        break
    for update in eighth_main_info:
        print(eighth_updated_at)
        break

DOGE
0.08158450038540539
-0.06765922242422288
-2.7706507773517357
-10.918262760241323
2023-02-13T15:12:12.268492

In [28]:
crytocurrency_df = crytocurrency_df.append({'coin': eighth_id,
                                            'price': eighth_price,
                                            'one hour change': eighth_change_1h,
                                            'one day change': eighth_change_24h,
                                            'one week change': eighth_change_7d,
                                            'update':eighth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/274332385.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': eighth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437
5,SOL,20.565613,0.398470,-2.245967,-11.069513,2023-02-13T15:11:14.823134
6,MATIC,1.168043,-0.109048,-8.656572,-2.958034,2023-02-13T15:12:14.154960
7,DOGE,0.081585,-0.067659,-2.770651,-10.918263,2023-02-13T15:12:12.268492

In [29]:
ninth_main_info = main_info['assets'][8]

ninth_id = main_info['assets'][8]['asset_id']
ninth_price = main_info['assets'][8]['price']
ninth_change_1h = main_info['assets'][8]['change_1h']
ninth_change_24h = main_info['assets'][8]['change_24h']
ninth_change_7d = main_info['assets'][8]['change_7d']

ninth_created_at =  main_info['assets'][8]['created_at']
ninth_description = main_info['assets'][8]['description']
ninth_updated_at = main_info['assets'][8]['updated_at']

In [30]:
class Ninth:

    for coin in ninth_main_info:
        print(ninth_id)
        break
    for price in ninth_main_info:
        print(ninth_price)
        break
    for one_hour_change in ninth_main_info:
        print(ninth_change_1h)
        break
    for one_day_change in ninth_main_info:
        print(ninth_change_24h)
        break
    for one_week_change in ninth_main_info:
        print(ninth_change_7d)
        break
    for update in ninth_main_info:
        print(ninth_updated_at)
        break

XRP
0.3697044237891722
0.14145986505819158
-3.165747723398056
-7.132582859198627
2023-02-13T15:11:16.012924

In [31]:
crytocurrency_df = crytocurrency_df.append({'coin': ninth_id,
                                            'price': ninth_price,
                                            'one hour change': ninth_change_1h,
                                            'one day change': ninth_change_24h,
                                            'one week change': ninth_change_7d,
                                            'update':ninth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/409097384.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': ninth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437
5,SOL,20.565613,0.398470,-2.245967,-11.069513,2023-02-13T15:11:14.823134
6,MATIC,1.168043,-0.109048,-8.656572,-2.958034,2023-02-13T15:12:14.154960
7,DOGE,0.081585,-0.067659,-2.770651,-10.918263,2023-02-13T15:12:12.268492
8,XRP,0.369704,0.141460,-3.165748,-7.132583,2023-02-13T15:11:16.012924

In [32]:
tenth_main_info = main_info['assets'][9]

tenth_id = main_info['assets'][9]['asset_id']
tenth_price = main_info['assets'][9]['price']
tenth_change_1h = main_info['assets'][9]['change_1h']
tenth_change_24h = main_info['assets'][9]['change_24h']
tenth_change_7d = main_info['assets'][9]['change_7d']

tenth_created_at =  main_info['assets'][9]['created_at']
tenth_description = main_info['assets'][9]['description']
tenth_updated_at = main_info['assets'][9]['updated_at']

In [33]:
class Tenth:
    for coin in tenth_main_info:
        print(tenth_id)
        break
    for price in tenth_main_info:
        print(tenth_price)
        break
    for one_hour_change in tenth_main_info:
        print(tenth_change_1h)
        break
    for one_day_change in tenth_main_info:
        print(tenth_change_24h)
        break
    for one_week_change in tenth_main_info:
        print(tenth_change_7d)
        break
    for update in tenth_main_info:
        print(tenth_updated_at)
        break

APT
13.464950125967734
0.8580164599355394
-0.8467927927845124
-10.979270185771073
2023-02-13T15:12:10.885473

In [34]:
crytocurrency_df = crytocurrency_df.append({'coin': tenth_id,
                                            'price': tenth_price,
                                            'one hour change': tenth_change_1h,
                                            'one day change': tenth_change_24h,
                                            'one week change': tenth_change_7d,
                                            'update':tenth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_52208/932090620.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': tenth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,1.000495,-0.013991,0.045998,0.050000,2023-02-13T15:11:15.461308
1,BTC,21623.895096,0.053197,-1.264811,-5.328867,2023-02-13T15:12:11.607444
2,BUSD,0.998500,-0.100050,-0.100050,-0.100050,2023-02-13T15:12:11.696055
3,ETH,1484.030000,0.161646,-3.076167,-8.912763,2023-02-13T15:12:12.474254
4,BNB,290.297881,-0.164738,-6.128171,-11.577925,2023-02-13T15:12:11.471437
5,SOL,20.565613,0.398470,-2.245967,-11.069513,2023-02-13T15:11:14.823134
6,MATIC,1.168043,-0.109048,-8.656572,-2.958034,2023-02-13T15:12:14.154960
7,DOGE,0.081585,-0.067659,-2.770651,-10.918263,2023-02-13T15:12:12.268492
8,XRP,0.369704,0.141460,-3.165748,-7.132583,2023-02-13T15:11:16.012924
9,APT,13.464950,0.858016,-0.846793,-10.979270,2023-02-13T15:12:10.885473