In [1]:
import requests
from pprint import pprint as pp
import pandas as pd

In [2]:
# https://cryptingup.com/apidoc/#introduction
response = requests.get('https://cryptingup.com/api/assets/?ID=btc')
main_info = response.json()

In [3]:
crytocurrency_df = pd.DataFrame(columns=['coin','price','one hour change','one day change', 'one week change', 'update'])
crytocurrency_df

Empty DataFrame
Columns: [coin, price, one hour change, one day change, one week change, update]
Index: []

In [4]:
first_main_info = main_info['assets'][0]

first_id = main_info['assets'][0]['asset_id']
first_price = main_info['assets'][0]['price']
first_change_1h = main_info['assets'][0]['change_1h']
first_change_24h = main_info['assets'][0]['change_24h']
first_change_7d = main_info['assets'][0]['change_7d']

first_created_at = main_info['assets'][0]['created_at']
first_description = main_info['assets'][0]['description']
first_updated_at = main_info['assets'][0]['updated_at']

In [5]:
def get_first_currency(main_info):
    first_main_info = main_info['assets'][0]
    first_id = main_info['assets'][0]['asset_id']
    first_price = main_info['assets'][0]['price']
    first_change_1h = main_info['assets'][0]['change_1h']
    first_change_24h = main_info['assets'][0]['change_24h']
    first_change_7d = main_info['assets'][0]['change_7d']
    first_created_at = main_info['assets'][0]['created_at']
    first_description = main_info['assets'][0]['description']
    first_updated_at = main_info['assets'][0]['updated_at']

    return first_main_info, first_id, first_price, first_change_1h, first_change_24h, first_change_7d, first_updated_at

In [6]:
get_first_currency(main_info)

({'quote': {'EUR': {'price': 0.9328506690680535,
    'volume_24h': 11369926251.185518,
    'market_cap': 63494137707.75424,
    'fully_diluted_market_cap': 63494137707.75424},
   'AUD': {'price': 1.4560787195877738,
    'volume_24h': 17747221722.17884,
    'market_cap': 99107462534.38338,
    'fully_diluted_market_cap': 99107462534.38338},
   'USD': {'price': 0.9999950000122065,
    'volume_24h': 12188305994.411623,
    'market_cap': 68064291899.2308,
    'fully_diluted_market_cap': 68064291899.2308},
   'GBP': {'price': 0.8327804875485598,
    'volume_24h': 10150234159.464045,
    'market_cap': 56682897606.28504,
    'fully_diluted_market_cap': 56682897606.28504},
   'JPY': {'price': 132.76348986029552,
    'volume_24h': 1618170130134.145,
    'market_cap': 9036498109791.967,
    'fully_diluted_market_cap': 9036498109791.967},
   'NZD': {'price': 1.591593042014428,
    'volume_24h': 19398920009.011536,
    'market_cap': 108331195051.10764,
    'fully_diluted_market_cap': 108331195051.10764},
   'CAD': {'price': 1.3444235853906288,
    'volume_24h': 16386327976.284828,
    'market_cap': 91507696889.60565,
    'fully_diluted_market_cap': 91507696889.60565}},
  'asset_id': 'USDT',
  'name': 'Tether',
  'description': 'Launched in 2014, Tether is a blockchain-enabled platform designed to facilitate the use of fiat currencies in a digital manner. Tether works to disrupt the conventional financial system via a more modern approach to money. Tether has made headway by giving customers the ability to transact with traditional currencies across the blockchain, without the inherent volatility and complexity typically associated with a digital currency. As the first blockchain-enabled platform to facilitate the digital use of traditional currencies (a familiar, stable accounting unit), Tether has democratised cross-border transactions across the blockchain.',
  'website': '',
  'ethereum_contract_address': '',
  'pegged': 'USD',
  'price': 0.9999950000122065,
  'volume_24h': 12188305994.411623,
  'change_1h': 0.003000107879478152,
  'change_24h': -0.02899173800205508,
  'change_7d': 0.0009898977221508172,
  'total_supply': 68064632221.56107,
  'circulating_supply': 68064632221.56107,
  'max_supply': 0,
  'market_cap': 68064291899.2308,
  'fully_diluted_market_cap': 68064291899.2308,
  'status': 'recent',
  'created_at': '2021-09-21T01:53:50',
  'updated_at': '2023-02-06T17:06:17.561672'},
 'USDT',
 0.9999950000122065,
 0.003000107879478152,
 -0.02899173800205508,
 0.0009898977221508172,
 '2023-02-06T17:06:17.561672')

In [7]:
class First:

    for coin in first_main_info:
        print(first_id)
        break
    for price in first_main_info:
        print(first_price)
        break
    for one_hour_change in first_main_info:
        print(first_change_1h)
        break
    for one_day_change in first_main_info:
        print(first_change_24h)
        break
    for one_week_change in first_main_info:
        print(first_change_7d)
        break
    for update in first_main_info:
        print(first_updated_at)
        break

USDT
0.9999950000122065
0.003000107879478152
-0.02899173800205508
0.0009898977221508172
2023-02-06T17:06:17.561672

In [8]:
crytocurrency_df = crytocurrency_df.append({'coin': first_id,
                                            'price': first_price,
                                            'one hour change': first_change_1h,
                                            'one day change': first_change_24h,
                                            'one week change': first_change_7d,
                                            'update':first_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/2166909319.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': first_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003,-0.028992,0.00099,2023-02-06T17:06:17.561672

In [9]:
second_main_info = main_info['assets'][1]

second_id = main_info['assets'][1]['asset_id']
second_price = main_info['assets'][1]['price']
second_change_1h = main_info['assets'][1]['change_1h']
second_change_24h = main_info['assets'][1]['change_24h']
second_change_7d = main_info['assets'][1]['change_7d']

second_created_at = main_info['assets'][1]['created_at']
second_description = main_info['assets'][1]['description']
second_updated_at = main_info['assets'][1]['updated_at']

In [10]:
class Second:

    for coin in second_main_info:
        print(second_id)
        break
    for price in second_main_info:
        print(second_price)
        break
    for one_hour_change in second_main_info:
        print(second_change_1h)
        break
    for one_day_change in second_main_info:
        print(second_change_24h)
        break
    for one_week_change in second_main_info:
        print(second_change_7d)
        break
    for update in second_main_info:
        print(second_updated_at)
        break

BTC
22988.18
-0.262812459935459
0.5582518258533541
-0.8232237851554768
2023-02-06T17:06:12.384193

In [11]:
crytocurrency_df = crytocurrency_df.append({'coin': second_id,
                                            'price': second_price,
                                            'one hour change': second_change_1h,
                                            'one day change': second_change_24h,
                                            'one week change': second_change_7d,
                                            'update':second_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/403869589.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': second_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193

In [12]:
third_main_info = main_info['assets'][2]

third_id = main_info['assets'][2]['asset_id']
third_price = main_info['assets'][2]['price']
third_change_1h = main_info['assets'][2]['change_1h']
third_change_24h = main_info['assets'][2]['change_24h']
third_change_7d = main_info['assets'][2]['change_7d']

third_created_at = main_info['assets'][2]['created_at']
third_description = main_info['assets'][2]['description']
third_updated_at = main_info['assets'][2]['updated_at']

In [13]:
class Third:

    for coin in third_main_info:
        print(third_id)
        break
    for price in third_main_info:
        print(third_price)
        break
    for one_hour_change in third_main_info:
        print(third_change_1h)
        break
    for one_day_change in third_main_info:
        print(third_change_24h)
        break
    for one_week_change in third_main_info:
        print(third_change_7d)
        break
    for update in third_main_info:
        print(third_updated_at)
        break

BUSD
0.9995000000000002
0
0
-0.09995002498748415
2023-02-06T17:06:12.485198

In [14]:
crytocurrency_df = crytocurrency_df.append({'coin': third_id,
                                            'price': third_price,
                                            'one hour change': third_change_1h,
                                            'one day change': third_change_24h,
                                            'one week change': third_change_7d,
                                            'update':third_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/1545298032.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': third_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198

In [15]:
fourth_main_info = main_info['assets'][3]

fourth_id = main_info['assets'][3]['asset_id']
fourth_price = main_info['assets'][3]['price']
fourth_change_1h = main_info['assets'][3]['change_1h']
fourth_change_24h = main_info['assets'][3]['change_24h']
fourth_change_7d = main_info['assets'][3]['change_7d']

fourth_created_at = main_info['assets'][3]['created_at']
fourth_description = main_info['assets'][3]['description']
fourth_updated_at = main_info['assets'][3]['updated_at']

In [16]:
class Fourth:

    for coin in fourth_main_info:
        print(fourth_id)
        break
    for price in fourth_main_info:
        print(fourth_price)
        break
    for one_hour_change in fourth_main_info:
        print(fourth_change_1h)
        break
    for one_day_change in fourth_main_info:
        print(fourth_change_24h)
        break
    for one_week_change in fourth_main_info:
        print(fourth_change_7d)
        break
    for update in fourth_main_info:
        print(fourth_updated_at)
        break

ETH
1644.2960492260618
-0.3008771354590478
1.7157451146918037
3.85579423298475
2023-02-06T17:06:13.375321

In [17]:
crytocurrency_df = crytocurrency_df.append({'coin': fourth_id,
                                            'price': fourth_price,
                                            'one hour change': fourth_change_1h,
                                            'one day change': fourth_change_24h,
                                            'one week change': fourth_change_7d,
                                            'update':fourth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/462955676.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': fourth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321

In [18]:
fifth_main_info = main_info['assets'][4]

fifth_id = main_info['assets'][4]['asset_id']
fifth_price = main_info['assets'][4]['price']
fifth_change_1h = main_info['assets'][4]['change_1h']
fifth_change_24h = main_info['assets'][4]['change_24h']
fifth_change_7d = main_info['assets'][4]['change_7d']

fifth_created_at =  main_info['assets'][4]['created_at']
fifth_description = main_info['assets'][4]['description']
fifth_updated_at = main_info['assets'][4]['updated_at']

In [19]:
class Fifth:

    for coin in fifth_main_info:
        print(fifth_id)
        break
    for price in fifth_main_info:
        print(fifth_price)
        break
    for one_hour_change in fifth_main_info:
        print(fifth_change_1h)
        break
    for one_day_change in fifth_main_info:
        print(fifth_change_24h)
        break
    for one_week_change in fifth_main_info:
        print(fifth_change_7d)
        break
    for update in fifth_main_info:
        print(fifth_updated_at)
        break

APT
15.420920011060826
-1.888722042641355
3.376548095590224
-12.885495509571063
2023-02-06T17:06:11.687172

In [20]:
crytocurrency_df = crytocurrency_df.append({'coin': fifth_id,
                                            'price': fifth_price,
                                            'one hour change': fifth_change_1h,
                                            'one day change': fifth_change_24h,
                                            'one week change': fifth_change_7d,
                                            'update':fifth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/1698772274.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': fifth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172

In [21]:
sixth_main_info = main_info['assets'][5]

sixth_id = main_info['assets'][5]['asset_id']
sixth_price = main_info['assets'][5]['price']
sixth_change_1h = main_info['assets'][5]['change_1h']
sixth_change_24h = main_info['assets'][5]['change_24h']
sixth_change_7d = main_info['assets'][5]['change_7d']

sixth_created_at =  main_info['assets'][5]['created_at']
sixth_description = main_info['assets'][5]['description']
sixth_updated_at = main_info['assets'][5]['updated_at']

In [22]:
class Sixth:

    for coin in sixth_main_info:
        print(sixth_id)
        break
    for price in sixth_main_info:
        print(sixth_price)
        break
    for one_hour_change in sixth_main_info:
        print(sixth_change_1h)
        break
    for one_day_change in sixth_main_info:
        print(sixth_change_24h)
        break
    for one_week_change in sixth_main_info:
        print(sixth_change_7d)
        break
    for update in sixth_main_info:
        print(sixth_updated_at)
        break

SHIB
1.4364840506377595e-05
-1.3061275925927063
1.664027925920132
23.459728492965283
2023-02-06T17:06:16.651984

In [23]:
crytocurrency_df = crytocurrency_df.append({'coin': sixth_id,
                                            'price': sixth_price,
                                            'one hour change': sixth_change_1h,
                                            'one day change': sixth_change_24h,
                                            'one week change': sixth_change_7d,
                                            'update':sixth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/3619653181.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': sixth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172
5,SHIB,0.000014,-1.306128,1.664028,23.459728,2023-02-06T17:06:16.651984

In [24]:
seventh_main_info = main_info['assets'][6]

seventh_id = main_info['assets'][6]['asset_id']
seventh_price = main_info['assets'][6]['price']
seventh_change_1h = main_info['assets'][6]['change_1h']
seventh_change_24h = main_info['assets'][6]['change_24h']
seventh_change_7d = main_info['assets'][6]['change_7d']

seventh_created_at =  main_info['assets'][6]['created_at']
seventh_description = main_info['assets'][6]['description']
seventh_updated_at = main_info['assets'][6]['updated_at']

In [25]:
class Seventh:

    for coin in seventh_main_info:
        print(seventh_id)
        break
    for price in seventh_main_info:
        print(seventh_price)
        break
    for one_hour_change in seventh_main_info:
        print(seventh_change_1h)
        break
    for one_day_change in seventh_main_info:
        print(seventh_change_24h)
        break
    for one_week_change in seventh_main_info:
        print(seventh_change_7d)
        break
    for update in seventh_main_info:
        print(seventh_updated_at)
        break

FET
0.45069141627635284
2.8087129228974472
2.157528059421358
66.06804565804441
2023-02-06T17:06:13.552500

In [26]:
crytocurrency_df = crytocurrency_df.append({'coin': seventh_id,
                                            'price': seventh_price,
                                            'one hour change': seventh_change_1h,
                                            'one day change': seventh_change_24h,
                                            'one week change': seventh_change_7d,
                                            'update':seventh_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/2530204870.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': seventh_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172
5,SHIB,0.000014,-1.306128,1.664028,23.459728,2023-02-06T17:06:16.651984
6,FET,0.450691,2.808713,2.157528,66.068046,2023-02-06T17:06:13.552500

In [27]:
eighth_main_info = main_info['assets'][7]

eighth_id = main_info['assets'][7]['asset_id']
eighth_price = main_info['assets'][7]['price']
eighth_change_1h = main_info['assets'][7]['change_1h']
eighth_change_24h = main_info['assets'][7]['change_24h']
eighth_change_7d = main_info['assets'][7]['change_7d']

eighth_created_at =  main_info['assets'][7]['created_at']
eighth_description = main_info['assets'][7]['description']
eighth_updated_at = main_info['assets'][7]['updated_at']

In [28]:
class Eighth:

    for coin in eighth_main_info:
        print(eighth_id)
        break
    for price in eighth_main_info:
        print(eighth_price)
        break
    for one_hour_change in eighth_main_info:
        print(eighth_change_1h)
        break
    for one_day_change in eighth_main_info:
        print(eighth_change_24h)
        break
    for one_week_change in eighth_main_info:
        print(eighth_change_7d)
        break
    for update in eighth_main_info:
        print(eighth_updated_at)
        break

AGIX
0.4403889257992819
-1.6140776706551796
3.8223087244512732
157.5526579842761
2023-02-06T17:06:11.489635

In [29]:
crytocurrency_df = crytocurrency_df.append({'coin': eighth_id,
                                            'price': eighth_price,
                                            'one hour change': eighth_change_1h,
                                            'one day change': eighth_change_24h,
                                            'one week change': eighth_change_7d,
                                            'update':eighth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/274332385.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': eighth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172
5,SHIB,0.000014,-1.306128,1.664028,23.459728,2023-02-06T17:06:16.651984
6,FET,0.450691,2.808713,2.157528,66.068046,2023-02-06T17:06:13.552500
7,AGIX,0.440389,-1.614078,3.822309,157.552658,2023-02-06T17:06:11.489635

In [30]:
ninth_main_info = main_info['assets'][8]

ninth_id = main_info['assets'][8]['asset_id']
ninth_price = main_info['assets'][8]['price']
ninth_change_1h = main_info['assets'][8]['change_1h']
ninth_change_24h = main_info['assets'][8]['change_24h']
ninth_change_7d = main_info['assets'][8]['change_7d']

ninth_created_at =  main_info['assets'][8]['created_at']
ninth_description = main_info['assets'][8]['description']
ninth_updated_at = main_info['assets'][8]['updated_at']

In [31]:
class Ninth:

    for coin in ninth_main_info:
        print(ninth_id)
        break
    for price in ninth_main_info:
        print(ninth_price)
        break
    for one_hour_change in ninth_main_info:
        print(ninth_change_1h)
        break
    for one_day_change in ninth_main_info:
        print(ninth_change_24h)
        break
    for one_week_change in ninth_main_info:
        print(ninth_change_7d)
        break
    for update in ninth_main_info:
        print(ninth_updated_at)
        break

HOOK
3.6824383226294524
-3.716272787747031
13.368561513284735
20.866601664188426
2023-02-06T17:06:14.160168

In [32]:
crytocurrency_df = crytocurrency_df.append({'coin': ninth_id,
                                            'price': ninth_price,
                                            'one hour change': ninth_change_1h,
                                            'one day change': ninth_change_24h,
                                            'one week change': ninth_change_7d,
                                            'update':ninth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/409097384.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': ninth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172
5,SHIB,0.000014,-1.306128,1.664028,23.459728,2023-02-06T17:06:16.651984
6,FET,0.450691,2.808713,2.157528,66.068046,2023-02-06T17:06:13.552500
7,AGIX,0.440389,-1.614078,3.822309,157.552658,2023-02-06T17:06:11.489635
8,HOOK,3.682438,-3.716273,13.368562,20.866602,2023-02-06T17:06:14.160168

In [33]:
tenth_main_info = main_info['assets'][9]

tenth_id = main_info['assets'][9]['asset_id']
tenth_price = main_info['assets'][9]['price']
tenth_change_1h = main_info['assets'][9]['change_1h']
tenth_change_24h = main_info['assets'][9]['change_24h']
tenth_change_7d = main_info['assets'][9]['change_7d']

tenth_created_at =  main_info['assets'][9]['created_at']
tenth_description = main_info['assets'][9]['description']
tenth_updated_at = main_info['assets'][9]['updated_at']

In [34]:
class Tenth:
    for coin in tenth_main_info:
        print(tenth_id)
        break
    for price in tenth_main_info:
        print(tenth_price)
        break
    for one_hour_change in tenth_main_info:
        print(tenth_change_1h)
        break
    for one_day_change in tenth_main_info:
        print(tenth_change_24h)
        break
    for one_week_change in tenth_main_info:
        print(tenth_change_7d)
        break
    for update in tenth_main_info:
        print(tenth_updated_at)
        break

BNB
328.1744733378336
-0.8629143762731483
0.6880433766699713
6.049110238365034
2023-02-06T17:06:12.221713

In [35]:
crytocurrency_df = crytocurrency_df.append({'coin': tenth_id,
                                            'price': tenth_price,
                                            'one hour change': tenth_change_1h,
                                            'one day change': tenth_change_24h,
                                            'one week change': tenth_change_7d,
                                            'update':tenth_updated_at}, ignore_index=True)
crytocurrency_df

/var/folders/02/lzvd5scj4zb274qzdzm7r7p80000gn/T/ipykernel_5129/932090620.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  crytocurrency_df = crytocurrency_df.append({'coin': tenth_id,

,coin,price,one hour change,one day change,one week change,update
0,USDT,0.999995,0.003000,-0.028992,0.000990,2023-02-06T17:06:17.561672
1,BTC,22988.180000,-0.262812,0.558252,-0.823224,2023-02-06T17:06:12.384193
2,BUSD,0.999500,0.000000,0.000000,-0.099950,2023-02-06T17:06:12.485198
3,ETH,1644.296049,-0.300877,1.715745,3.855794,2023-02-06T17:06:13.375321
4,APT,15.420920,-1.888722,3.376548,-12.885496,2023-02-06T17:06:11.687172
5,SHIB,0.000014,-1.306128,1.664028,23.459728,2023-02-06T17:06:16.651984
6,FET,0.450691,2.808713,2.157528,66.068046,2023-02-06T17:06:13.552500
7,AGIX,0.440389,-1.614078,3.822309,157.552658,2023-02-06T17:06:11.489635
8,HOOK,3.682438,-3.716273,13.368562,20.866602,2023-02-06T17:06:14.160168
9,BNB,328.174473,-0.862914,0.688043,6.049110,2023-02-06T17:06:12.221713